version: "3.8"
services:
  mysql:
    image: mysql:8
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=sessions
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - main

networks:
  main: