spring:
  main:
    banner-mode: off
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate.hbm2ddl.auto: create

tcc:
  feature-flag:
    enabled: true
    flags:
      personal-number-manager.enabled: ${FF_PERSONAL_NUMBER_MANAGER_ENABLED}